---
title: "p8105_hw5_ra2965"
author: Ran An
data: 11/06/2019
output: github_document
---
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```
#Problem1
```{r}

fill_missing = function(x){
  if (is.numeric(x)) {
    x = replace_na(x, mean(x, na.rm = TRUE))
  } else if (is.character(x)) {
    x = replace_na(x, "virginica")
  }
}

output_iris = map_df(iris_with_missing,fill_missing)
```
#Problem2
```{r message = FALSE, warning=FALSE}
hw5 = list.files(path = "./data") 

data_files =  data_frame(files = hw5) %>%  
  mutate(
    data = map(files, ~read_csv(str_c("./data/", .x)))
  ) %>% 
  unnest(cols = data) %>% 
  pivot_longer( 
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "data"
  ) %>% 
  mutate(
    control_arm = str_extract(files, "[:lower:]{3}"),
    subject_id = str_extract(files, "\\d{2}")
  ) %>% 
  select(control_arm,subject_id,everything()) %>% 
  select(-files) %>% 
  mutate(
   control_arm = recode(control_arm, con = "control", exp = "experimental")
  )
```

```{r}

data_files %>% 
  mutate(arm_id = str_c(control_arm,'_',subject_id)) %>% 
  ggplot(aes(x = week, y = data, color = control_arm, group = arm_id)) +
  geom_line() +
  labs(
    title = "Observations on each subject over weeks",
    x = "Week",
    y = "Observed data"
  ) + theme(
    legend.position = "bottom"
  )
  
```

```{r}
sim_regression = function(n, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 50)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
}

output = vector("list", 10000)

for (i in 1:10000) {
  output[[i]] = sim_regression(30)
}

sim_results = rerun(10000, sim_regression(30, 2, 0)) 

estimates = map_df(.x = sim_results, ~broom::tidy(.x)) %>% 
  filter(term == "x") %>% 
  janitor::clean_names() %>% 
  select(estimate,p_value)

```

